# Download Kafka.
# wget https://archive.apache.org/dist/kafka/2.8.0/kafka_2.12-2.8.0.tgz

# Extract Kafka.
# tar -xzf kafka_2.12-2.8.0.tgz

# Start MySQL server.
# start_mysql
# mysql --host=127.0.0.1 --port=3306 --user=root --password=ODAyNy1udXI4OWF5

# Create a database named tolldata.
# create database tolldata;

# Create a table named livetolldata with the schema to store the data generated by the traffic simulator.
# use tolldata;
# create table livetolldata(timestamp datetime,vehicle_id int,vehicle_type char(15),toll_plaza_id smallint);

# Disconnect from MySQL server.
# exit

# Install the python module kafka-python using the pip command.
# python3 -m pip install kafka-python
# This python module will help you to communicate with kafka server. It can used to send and receive messages from kafka. 

# Install the python module mysql-connector-python using the pip command.
# python3 -m pip install mysql-connector-python==8.0.31
# This python module will help you to interact with mysql server.

# Start the ZooKeeper server.
# docker run --name myzookeeper --restart always zookeeper

# Start the Kafka broker service
# docker run --name mykafkaserver --link myzookeeper:zookeeper apache/kafka

# Create a Kakfa topic named toll
# docker exec -it mykafkaserver /opt/kafka/bin/kafka-topics.sh --create --topic toll --bootstrap-server localhost:9092

# Download the Toll Traffic Simulator
# toll_traffic_generator.py

# Run the Toll Traffic Simulator
# python3 toll_traffic_generator.py